services:

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: "run-tracker"
      POSTGRES_PASSWORD: "!QAZxsw2"
      POSTGRES_DB: "run-tracker"
    networks:
      - common

  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgres:5432/run-tracker
    networks:
      - common

networks:
  common: {}